// front/components/Footer/index.vue
<template>
  <footer class="py-2 bg-lighter">
    <div class="container text-center">
      <ul class="nav justify-content-center mb-3">
        <li class="nav-item">
          <NuxtLink to="/terms_of_service">
            利用規約
          </NuxtLink>
        </li>
        <li class="nav-item">
          <NuxtLink to="/contact">
            お問い合わせ
          </NuxtLink>
        </li>
      </ul>
      <small>Copyright &copy;上場企業ランキング</small>
    </div>
  </footer>
</template>

<script lang='ts'>
import { defineComponent } from '@nuxtjs/composition-api'

export default defineComponent({
  setup () {
    return {
    }
  }
})
</script>

<style lang="scss" scoped>
.nav {
  gap: 3rem;
}
</style>

// typescript/components/Footer.tsx
import Link from 'next/link'

export default function Footer() {
  return (
    <footer className="py-2  bg-base-300">
      <div className="container text-center">
        <ul className="flex justify-center mb-3 space-x-4">
          <li>
            <Link href={{ pathname: "/terms_of_service" }}>利用規約</Link>
          </li>
          <li>
            <Link href={{ pathname: "/contact" }}>お問い合わせ</Link>
          </li>
        </ul>
        {/* <small className="">Copyright &copy;上場企業ランキング</small> */}
      </div>
    </footer>
  )
}
